server:
  port: 8888

spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/victorherrerocazurro/RepositorioConfiguraciones

endpoints:
  beans:
    sensitive: false
  refresh:
    sensitive: false